version: '3'
services:
  front:
    build: front/
    container_name: front
    restart: always
    ports:
      - '3000:3000'
    networks: 
      - ext 

  back:
    build: back/
    container_name: back
    restart: always
    ports:
      - '3001:3001'
    networks: 
      - ext 

  postgres:
    image: postgres:latest
    container_name: pg 
    restart: always
    environment:
      - POSTGRES_USER=autobase
      - POSTGRES_PASSWORD=1234567
    ports
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks: 
      - ext 
networks:
  ext:
    driver: bridge
    name: ext
#    external: true
volumes:
  pg_data: